### ISSUE TITLE
Bump actions/setup-node to v3

### ISSUE THREAD

**Issue by klein0r** [ioBroker/testing-action-adapter#2]
https://github.com/ioBroker/testing-action-adapter/blob/c4ef8d8ac14960d8dc7a34462670c7d4b5bbeb81/action.yml#L35

Reason:

> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[210](https://github.com/iobroker-community-adapters/ioBroker.statistics/actions/runs/3573315820/jobs/6007233128#step:2:220)

**Comment by klein0r** [comment]
see https://github.com/actions/setup-node/issues/589

**Comment by AlCalzone** [comment]
Wanna make a PR?
