### ISSUE TITLE
Enforce nodeJs engines check

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/testing-action-adapter#9]
Currently standard tests pass even if the test is run at node 18 and either the adapter code specifies nodeJs 20 or any dependency specifies nodeJs 20. Only a warning is logged.

Workflow should install environment using 'engine-strict=true' to cause an error

**Comment by AlCalzone** [comment]
Moved the issue to the correct repo

**Comment by mcm1957** [comment]
Solved if default inctall command is used by https://github.com/ioBroker/testing-action-adapter/pull/10

**Comment by mcm1957** [comment]
close here as issue #8 refers to same problem.
